# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_activities', '0005_auto_20170903_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='name',
            new_name='title',
        ),
    ]
