# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_activities', '0008_auto_20171025_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='level',
            field=models.CharField(default=21, max_length=100, verbose_name=b'Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extra',
            name='month',
            field=models.CharField(default=21, max_length=10, verbose_name=b'Month'),
            preserve_default=False,
        ),
    ]
