# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_activities', '0010_auto_20171108_1441'),
        ('extra_activities', '0010_auto_20171108_2213'),
    ]

    operations = [
    ]
