# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_activities', '0011_merge_20171109_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role'),
        ),
    ]
