# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_merge_20170901_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_book', models.CharField(max_length=100, verbose_name='Book Title')),
                ('isbn', models.CharField(max_length=100, verbose_name='ISBN')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('author', models.ManyToManyField(related_name='employee_book_author', to='employee.Employee', verbose_name='Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100, verbose_name='Paper Title')),
                ('book_title_and_publisher', models.CharField(max_length=100, verbose_name='Book Title with Publisher')),
                ('page_no', models.CharField(max_length=100, verbose_name='Page No.')),
                ('isbn', models.CharField(max_length=100, verbose_name='ISBN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('author', models.ManyToManyField(related_name='employee_bc_author', to='employee.Employee', verbose_name='Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book_chapter', to='employee.Employee')),
            ],
            options={
                'db_table': 'book_chapters',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100, verbose_name='Paper Title')),
                ('name_and_publisher', models.CharField(max_length=100, verbose_name='Name & Publisher')),
                ('volume_no', models.CharField(max_length=100, verbose_name='Vol no')),
                ('issn_isbn', models.CharField(max_length=100, verbose_name='ISBN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('international_national', models.CharField(max_length=100, verbose_name='International/National')),
                ('author', models.ManyToManyField(related_name='employee_conf_author', to='employee.Employee', verbose_name='Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_conf', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='JournalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100, verbose_name='Paper Title')),
                ('name_and_publisher', models.CharField(max_length=100, verbose_name='Journal Name with Publisher')),
                ('volume_no', models.CharField(max_length=100, verbose_name='Vol. No.')),
                ('issn_isbn', models.CharField(max_length=100, verbose_name='ISSN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('author', models.ManyToManyField(related_name='employee_jp_author', to='employee.Employee', verbose_name='Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jp', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'publication_details',
            },
        ),
    ]
