# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_book', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='BookChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100)),
                ('book_title_and_publisher', models.CharField(max_length=100)),
                ('page_no', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('indexing', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book_chapter_author', to='employee.Employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book_chapter', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100)),
                ('name_and_publisher', models.CharField(max_length=100)),
                ('volume_no', models.CharField(max_length=100)),
                ('issn_isbn', models.CharField(max_length=100)),
                ('indexing', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('international_national', models.CharField(max_length=100)),
                ('author', models.ManyToManyField(related_name='employee_conf_author', to='employee.Employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_conf', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='JournalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=100)),
                ('name_and_publisher', models.CharField(max_length=100)),
                ('volume_no', models.CharField(max_length=100)),
                ('issn_isbn', models.CharField(max_length=100)),
                ('indexing', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('author', models.ManyToManyField(related_name='employee_jp_author', to='employee.Employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jp', to='employee.Employee')),
            ],
        ),
    ]
