# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_auto_20170903_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Book')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('coauthor', models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book', to='employee.Employee')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Book Chapter')),
                ('book_title_and_publisher', models.CharField(max_length=100, verbose_name='Book Title with Publisher')),
                ('page_no', models.IntegerField(verbose_name='Page No.')),
                ('isbn', models.IntegerField(verbose_name='ISBN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('coauthor', models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book_chapter', to='employee.Employee')),
            ],
            options={
                'db_table': 'book_chapters',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Paper')),
                ('name_and_publisher', models.CharField(max_length=100, verbose_name='Name & Publisher')),
                ('volume_no', models.CharField(max_length=100, verbose_name='Vol no')),
                ('issue_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Issue no')),
                ('issn_isbn', models.IntegerField(verbose_name='ISBN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('international_national', models.CharField(max_length=100, verbose_name='International/National')),
                ('coauthor', models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors')),
                ('page_no_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Page number starting')),
                ('page_no_end', models.CharField(blank=True, max_length=100, null=True, verbose_name='Page number ending')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_conf', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='JournalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Paper')),
                ('name_and_publisher', models.CharField(max_length=100, verbose_name='Journal Name with Publisher')),
                ('volume_no', models.CharField(max_length=100, verbose_name='Vol. No.')),
                ('issn_isbn', models.IntegerField(verbose_name='ISSN No.')),
                ('indexing', models.CharField(max_length=100, verbose_name='Indexing')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('hindex', models.CharField(blank=True, max_length=100, null=True, verbose_name='H-Index of Journal using Scimago (if Scopus, SCI-Ex or SCI)')),
                ('impact_factor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Impact Factor if SCI-Ex or SCI')),
                ('coauthor', models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jp', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'journal_papers',
            },
        ),
    ]
