# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookchapters',
            table='book_chapters',
        ),
        migrations.AlterModelTable(
            name='conference',
            table='conference',
        ),
        migrations.AlterModelTable(
            name='journalpapers',
            table='publication_details',
        ),
    ]
