# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title_of_book',
        ),
        migrations.RemoveField(
            model_name='bookchapters',
            name='title_of_paper',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='title_of_paper',
        ),
        migrations.RemoveField(
            model_name='journalpapers',
            name='title_of_paper',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='bookchapters',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Book Chapter'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Paper'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Paper'),
        ),
    ]
