# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='volume_no',
        ),
        migrations.AddField(
            model_name='book',
            name='page_no_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Page number ending'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_no_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Page number starting'),
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
