# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='txt',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
