# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookchapters',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journalpapers',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='coauthor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors'),
        ),
        migrations.AddField(
            model_name='bookchapters',
            name='coauthor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors'),
        ),
        migrations.AddField(
            model_name='conference',
            name='coauthor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='coauthor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors'),
        ),
        migrations.DeleteModel(
            name='CoAuthors',
        ),
    ]
