# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0002_auto_20170909_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpapers',
            name='hindex',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='H-Index of Journal using Scimago (if Scopus, SCI-Ex or SCI)'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='impact_factor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Impact Factor if SCI-Ex or SCI'),
        ),
    ]
