# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0002_book_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='txt',
        ),
    ]
