# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0002_auto_20170825_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_of_book',
            field=models.CharField(max_length=100, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_book_chapter_author', to='employee.Employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='book_title_and_publisher',
            field=models.CharField(max_length=100, verbose_name='Book Title with Publisher'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='indexing',
            field=models.CharField(max_length=100, verbose_name='Indexing'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='isbn',
            field=models.CharField(max_length=100, verbose_name='ISBN No.'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='month',
            field=models.CharField(max_length=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='page_no',
            field=models.CharField(max_length=100, verbose_name='Page No.'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='title_of_paper',
            field=models.CharField(max_length=100, verbose_name='Paper Title'),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='author',
            field=models.ManyToManyField(related_name='employee_conf_author', to='employee.Employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_conf', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='indexing',
            field=models.CharField(max_length=100, verbose_name='Indexing'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='international_national',
            field=models.CharField(max_length=100, verbose_name='International/National'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='issn_isbn',
            field=models.CharField(max_length=100, verbose_name='ISBN No.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='month',
            field=models.CharField(max_length=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name_and_publisher',
            field=models.CharField(max_length=100, verbose_name='Name & Publisher'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title_of_paper',
            field=models.CharField(max_length=100, verbose_name='Paper Title'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='volume_no',
            field=models.CharField(max_length=100, verbose_name='Vol no'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='author',
            field=models.ManyToManyField(related_name='employee_jp_author', to='employee.Employee', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jp', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='indexing',
            field=models.CharField(max_length=100, verbose_name='Indexing'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='issn_isbn',
            field=models.CharField(max_length=100, verbose_name='ISSN No.'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='month',
            field=models.CharField(max_length=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='name_and_publisher',
            field=models.CharField(max_length=100, verbose_name='Journal Name with Publisher'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='title_of_paper',
            field=models.CharField(max_length=100, verbose_name='Paper Title'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='volume_no',
            field=models.CharField(max_length=100, verbose_name='Vol. No.'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
