# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0002_auto_20170825_2347'),
        ('publication_details', '0003_auto_20170911_1002'),
    ]

    operations = [
    ]
