# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0005_auto_20171107_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='issue_no',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name=b'Issue no'),
        ),
    ]
