# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0005_auto_20171009_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coauthor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_of_book',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title of Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
