# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0006_auto_20171009_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title_of_book',
            new_name='title',
        ),
    ]
