# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0006_auto_20171107_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_no_end',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name=b'Page number ending'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_no_start',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name=b'Page number starting'),
        ),
    ]
