# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0007_auto_20171009_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpapers',
            name='issn_isbn',
            field=models.IntegerField(verbose_name=b'ISSN No.'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='year',
            field=models.CharField(max_length=4, verbose_name=b'Year'),
        ),
    ]
