# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0009_merge_20171108_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_no_end',
            field=models.IntegerField(verbose_name='Page number ending'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_no_start',
            field=models.IntegerField(verbose_name='Page number starting'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='issue_no',
            field=models.IntegerField(verbose_name='Issue no'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='page_no_end',
            field=models.IntegerField(verbose_name='Page number ending'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='page_no_start',
            field=models.IntegerField(verbose_name='Page number starting'),
        ),
    ]
