# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0005_auto_20171108_2213'),
        ('publication_details', '0010_auto_20171109_1014'),
    ]

    operations = [
    ]
