# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0013_remove_bookchapters_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapters',
            name='indexing',
            field=models.CharField(default=None, max_length=100, verbose_name='Indexing'),
            preserve_default=False,
        ),
    ]
