# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0014_bookchapters_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpapers',
            name='ugcCheck',
            field=models.BooleanField(default=False),
        ),
    ]
