# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0015_journalpapers_ugc_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='month',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='conference',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='page_no_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page number ending'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='page_no_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page number starting'),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
