# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0016_auto_20180217_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpapers',
            name='hindex',
            field=models.IntegerField(blank=True, null=True, verbose_name='H-Index of Journal using Scimago (if Scopus, SCI-Ex or SCI)'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='impact_factor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Impact Factor if SCI-Ex or SCI'),
        ),
    ]
