# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0017_auto_20180217_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Institutional_Affiliation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institutional Affiliation As Mentioned'),
        ),
    ]
