# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0018_conference_institutional_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpapers',
            name='citation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalpapers',
            name='numcitations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
