# Generated by Django 3.0.2 on 2020-02-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication_details', '0019_auto_20180217_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookchapters',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_book_chapter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_conf', to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='journalpapers',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_jp', to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
    ]
