# Generated by Django 3.0.2 on 2020-02-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_details', '0020_auto_20200202_1259'),
        ('publication_details', '0007_auto_20171009_0905'),
    ]

    operations = [
    ]
