# Generated by Django 3.0.2 on 2020-02-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication_details', '0021_merge_20200202_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Year'),
        ),
    ]
