# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('insitute', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.Employee')),
            ],
        ),
    ]
