# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_lecturer', '0003_auto_20170826_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlecturer',
            name='year',
            field=models.TextField(blank=True, max_length='4', null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='institute',
            field=models.CharField(max_length=100, verbose_name='Institute Name'),
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='nature',
            field=models.CharField(max_length=100, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Topic'),
        ),
    ]
