# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_lecturer', '0004_auto_20170901_0556'),
        ('guest_lecturer', '0004_auto_20170831_1542'),
    ]

    operations = [
    ]
