# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_lecturer', '0006_auto_20170903_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestlecturer',
            old_name='topic',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='guestlecturer',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
