# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_lecturer', '0008_auto_20170903_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestLecturer',
            new_name='GuestLecture',
        ),
    ]
