# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_auto_20170903_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=100, verbose_name='Subject Code')),
                ('credit', models.IntegerField(verbose_name='Credit')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=200, verbose_name='Subject Name')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('sem', models.CharField(max_length=100, verbose_name='Semester')),
                ('mode', models.CharField(max_length=100, verbose_name='Type')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='File Name')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'subjects_taken',
            },
        ),
    ]
