# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_taken', '0003_auto_20171025_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectstaken',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course'),
        ),
    ]
