# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_taken', '0005_auto_20171026_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credit',
        ),
    ]
