# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_taken', '0006_remove_subject_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectstaken',
            old_name='title',
            new_name='subjects',
        ),
    ]
