# Generated by Django 3.0.2 on 2020-02-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects_taken', '0007_auto_20171105_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstaken',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
    ]
