# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_auto_20170825_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_patent', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Patent Name'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='patenting_agency',
            field=models.CharField(max_length=100, verbose_name='Patenting Agency'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='year_application',
            field=models.IntegerField(verbose_name='Year Of Application'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='year_grant',
            field=models.IntegerField(verbose_name='Year of Grant'),
        ),
    ]
