# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0006_auto_20171025_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='year_application',
            field=models.CharField(max_length=4, verbose_name=b'Year Of Application'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='year_grant',
            field=models.CharField(max_length=4, verbose_name=b'Year of Grant'),
        ),
    ]
