# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0008_auto_20171025_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patents',
            old_name='name',
            new_name='title',
        ),
    ]
