# Generated by Django 3.0.2 on 2020-02-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patents', '0009_auto_20171107_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_patent', to=settings.AUTH_USER_MODEL, verbose_name='Employee ID'),
        ),
    ]
