# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('instructor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('date_of_joining', models.DateField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
            ],
        ),
    ]
