# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_merge_20170901_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Date of Joining'),
        ),
    ]
