# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20170903_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.BooleanField(default=False, verbose_name='Awards')),
                ('extra_activities', models.BooleanField(default=False, verbose_name='Extra')),
                ('guest_lecturer', models.BooleanField(default=False, verbose_name='GuestLecturer')),
                ('moab', models.BooleanField(default=False, verbose_name='Membership')),
                ('patents', models.BooleanField(default=False, verbose_name='Patents')),
                ('professional_details', models.BooleanField(default=False, verbose_name='Professional')),
                ('project', models.BooleanField(default=False, verbose_name='Projects')),
                ('journal_papers', models.BooleanField(default=False, verbose_name='JournalPapers')),
                ('conference', models.BooleanField(default=False, verbose_name='Conference')),
                ('bookchapters', models.BooleanField(default=False, verbose_name='BookChapters')),
                ('book', models.BooleanField(default=False, verbose_name='Book')),
                ('subjects_taken', models.BooleanField(default=False, verbose_name='SubjectsTaken')),
                ('workshop', models.BooleanField(default=False, verbose_name='Workshop')),
                ('employee', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='employee_fs', to='employee.Employee')),
            ],
            options={
                'db_table': 'fill_status',
            },
        ),
    ]
