# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_experience', models.IntegerField()),
                ('industrial_exp', models.IntegerField()),
                ('qualification_before', models.CharField(max_length=100)),
                ('qualification_after', models.CharField(max_length=100)),
                ('phds', models.CharField(max_length=100)),
                ('pursuing', models.CharField(max_length=100)),
                ('submitted', models.CharField(max_length=100)),
                ('awarded', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
