# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='year',
            field=models.IntegerField(),
        ),
    ]
