# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0002_auto_20170817_1112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professional',
            table='professional',
        ),
    ]
