# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0007_auto_20170904_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phds',
            field=models.IntegerField(verbose_name=b'Total Student'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='submitted',
            field=models.IntegerField(verbose_name=b'Phd Submitted'),
        ),
    ]
