# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0010_auto_20171025_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='submitted',
            field=models.CharField(max_length=100, verbose_name='Phd Submitted'),
        ),
    ]
