# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0011_auto_20171026_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='qualification_before',
            new_name='qualification_highest',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='qualification_after',
        ),
        migrations.AddField(
            model_name='professional',
            name='qualification_year_completion',
            field=models.CharField(default=None, max_length=100, verbose_name='Year Of Completion of Highest Qualification'),
            preserve_default=False,
        ),
    ]
