# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0012_auto_20171105_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='year',
            field=models.CharField(default=2017, max_length=4, verbose_name='Year'),
        ),
    ]
