# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0016_merge_20171109_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='qualification_highest',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='year',
        ),
        migrations.AddField(
            model_name='professional',
            name='acedemic_exp',
            field=models.IntegerField(default=1, verbose_name=b'Acedemic Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='pdf_college',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PDF College'),
        ),
        migrations.AddField(
            model_name='professional',
            name='pdf_specialization',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PDF Specialization'),
        ),
        migrations.AddField(
            model_name='professional',
            name='pdf_title',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PDF Title'),
        ),
        migrations.AddField(
            model_name='professional',
            name='pdf_year_acquiring',
            field=models.CharField(default=2017, max_length=4, verbose_name=b'PDF Year Acquiring'),
        ),
        migrations.AddField(
            model_name='professional',
            name='pdf_year_application',
            field=models.CharField(default=2017, max_length=4, verbose_name=b'PDF Year Application'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_college',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PhD College'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_specialization',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PhD Specialization'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_title',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'PhD Title'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_year_acquiring',
            field=models.CharField(default=2017, max_length=4, verbose_name=b'PhD Year Acquiring'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_year_application',
            field=models.CharField(default=2017, max_length=4, verbose_name=b'PhD Year Application'),
        ),
        migrations.AddField(
            model_name='professional',
            name='postgraduation_college',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Postgraduation College'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='postgraduation_course',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Postgraduation Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='postgraduation_stream',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Postgraduation Stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='postgraduation_year',
            field=models.CharField(default=2017, max_length=100, verbose_name=b'Postgraduation Year'),
        ),
        migrations.AddField(
            model_name='professional',
            name='undergraduation_college',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Undergraduation College'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='undergraduation_course',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Undergraduation Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='undergraduation_stream',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Undergraduation Stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='undergraduation_year',
            field=models.CharField(default=2017, max_length=100, verbose_name=b'Undergraduation Year'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='qualification_year_completion',
            field=models.CharField(default=2017, max_length=100, verbose_name=b'Year Of Completion of Highest Qualification'),
        ),
    ]
