# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0017_auto_20171117_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='acedemic_exp',
            field=models.CharField(default=b'null', max_length=4, verbose_name=b'Acedemic Experience'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_acquiring',
            field=models.CharField(default=b'null', max_length=4, verbose_name=b'PDF Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_application',
            field=models.CharField(default=b'null', max_length=4, verbose_name=b'PDF Year Application'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_acquiring',
            field=models.CharField(default=b'null', max_length=4, verbose_name=b'PhD Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_application',
            field=models.CharField(default=b'null', max_length=4, verbose_name=b'PhD Year Application'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postgraduation_year',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'Postgraduation Year'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='qualification_year_completion',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'Year Of Completion of Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='undergraduation_year',
            field=models.CharField(default=b'null', max_length=100, verbose_name=b'Undergraduation Year'),
        ),
    ]
