# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0018_auto_20171117_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='pdf_no',
            field=models.BooleanField(default=False, verbose_name=b'No PdF'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phd_no',
            field=models.BooleanField(default=False, verbose_name=b'No PhD'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_acquiring',
            field=models.CharField(default=b'', max_length=4, verbose_name=b'PDF Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_application',
            field=models.CharField(default=b'', max_length=4, verbose_name=b'PDF Year Application'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_acquiring',
            field=models.CharField(default=b'', max_length=4, verbose_name=b'PhD Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_application',
            field=models.CharField(default=b'', max_length=4, verbose_name=b'PhD Year Application'),
        ),
    ]
