# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0019_auto_20171117_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='awarded',
            field=models.IntegerField(default=0, verbose_name=b'Phd Awarded'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phds',
            field=models.IntegerField(default=0, verbose_name=b'Total Student'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pursuing',
            field=models.IntegerField(default=0, verbose_name=b'Phd Pursuing'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='submitted',
            field=models.IntegerField(default=0, verbose_name=b'Phd Submitted'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Highest Qualification'),
        ),
    ]
