# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0020_auto_20171117_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='acedemic_exp',
            field=models.CharField(default='null', max_length=4, verbose_name='Acedemic Experience'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='awarded',
            field=models.IntegerField(default=0, verbose_name='Phd Awarded'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_college',
            field=models.CharField(default='null', max_length=100, verbose_name='PDF College'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_no',
            field=models.BooleanField(default=False, verbose_name='No PdF'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_specialization',
            field=models.CharField(default='null', max_length=100, verbose_name='PDF Specialization'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_title',
            field=models.CharField(default='null', max_length=100, verbose_name='PDF Title'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_acquiring',
            field=models.CharField(default='', max_length=4, verbose_name='PDF Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pdf_year_application',
            field=models.CharField(default='', max_length=4, verbose_name='PDF Year Application'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_college',
            field=models.CharField(default='null', max_length=100, verbose_name='PhD College'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_no',
            field=models.BooleanField(default=False, verbose_name='No PhD'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_specialization',
            field=models.CharField(default='null', max_length=100, verbose_name='PhD Specialization'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_title',
            field=models.CharField(default='null', max_length=100, verbose_name='PhD Title'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_acquiring',
            field=models.CharField(default='', max_length=4, verbose_name='PhD Year Acquiring'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phd_year_application',
            field=models.CharField(default='', max_length=4, verbose_name='PhD Year Application'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phds',
            field=models.IntegerField(default=0, verbose_name='Total Student'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postgraduation_college',
            field=models.CharField(max_length=100, verbose_name='Postgraduation College'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postgraduation_course',
            field=models.CharField(max_length=100, verbose_name='Postgraduation Course'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postgraduation_stream',
            field=models.CharField(max_length=100, verbose_name='Postgraduation Stream'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postgraduation_year',
            field=models.CharField(default='null', max_length=100, verbose_name='Postgraduation Year'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='pursuing',
            field=models.IntegerField(default=0, verbose_name='Phd Pursuing'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='qualification_year_completion',
            field=models.CharField(default='null', max_length=100, verbose_name='Year Of Completion of Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='submitted',
            field=models.IntegerField(default=0, verbose_name='Phd Submitted'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='undergraduation_college',
            field=models.CharField(max_length=100, verbose_name='Undergraduation College'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='undergraduation_course',
            field=models.CharField(max_length=100, verbose_name='Undergraduation Course'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='undergraduation_stream',
            field=models.CharField(max_length=100, verbose_name='Undergraduation Stream'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='undergraduation_year',
            field=models.CharField(default='null', max_length=100, verbose_name='Undergraduation Year'),
        ),
    ]
