# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0021_auto_20171128_1728'),
        ('professional_details', '0021_auto_20180112_1411'),
    ]

    operations = [
    ]
