# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0022_merge_20180124_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='csrf_token',
            field=models.CharField(default='null', max_length=20, verbose_name='CSRF Token'),
        ),
    ]
