# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional_details', '0023_professional_csrf_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='csrf_token',
        ),
    ]
