# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sponsors', models.CharField(max_length=100)),
                ('date_of_award', models.DateField()),
                ('date_completed', models.DateField()),
                ('amnt_sanctioned', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('copi', models.ManyToManyField(related_name='employee_copi', to='employee.Employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_projects', to='employee.Employee')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pi', to='employee.Employee')),
            ],
        ),
    ]
