# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_auto_20170903_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('sponsors', models.CharField(max_length=100, verbose_name='Sponsoring Agency')),
                ('date_of_award', models.TextField(verbose_name='Date of Award')),
                ('date_completed', models.TextField(verbose_name='Date of Completed')),
                ('amnt_sanctioned', models.CharField(max_length=100, verbose_name='Amount Sanctioned')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Principle Investigator')),
                ('coauthor', models.TextField(blank=True, max_length=200, null=True, verbose_name='Co Principle Investigators')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_projects', to='employee.Employee', verbose_name='Employee ID')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
