# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='amnt_sanctioned',
            field=models.IntegerField(verbose_name=b'Amount Sanctioned'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sponsors',
            field=models.TextField(verbose_name=b'Sponsoring Agency'),
        ),
    ]
