# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_merge_20170901_1138'),
        ('project', '0005_auto_20170903_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='copi',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='pi',
        ),
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.ManyToManyField(related_name='employee_copi', to='employee.Employee', verbose_name='Co Authors'),
        ),
    ]
