# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170903_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_completed',
            field=models.TextField(verbose_name='Date of Completed'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_of_award',
            field=models.TextField(verbose_name='Date of Award'),
        ),
    ]
