# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20171025_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='copi',
            new_name='coauthor',
        ),
    ]
