# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20170903_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='name',
            new_name='title',
        ),
    ]
