# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20170903_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
