# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20170903_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.IntegerField(max_length=100, verbose_name=b'Duration(in days)'),
        ),
    ]
