# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20171025_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.IntegerField(verbose_name='Duration(in days)'),
        ),
    ]
