# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_auto_20171025_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(max_length=100, verbose_name=b'Duration(in days)'),
        ),
    ]
