# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20171108_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Duration(in days)'),
        ),
    ]
