# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_auto_20171109_1014'),
        ('workshop', '0013_auto_20171109_2008'),
    ]

    operations = [
    ]
