# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_auto_20171110_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='detailsworkshop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
