# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0002_auto_20170825_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='academic_body',
            field=models.CharField(max_length=100, verbose_name='Academic Body Name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_moab', to='employee.Employee', verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='university_agency',
            field=models.CharField(max_length=100, verbose_name='University Agency'),
        ),
    ]
