# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0005_auto_20170903_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='type',
            new_name='title',
        ),
    ]
