# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0006_auto_20170903_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end_year',
            field=models.TextField(blank=True, max_length='10', null=True, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_year',
            field=models.TextField(blank=True, max_length='10', null=True, verbose_name='Start Year'),
        ),
    ]
