# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0007_auto_20171025_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_year',
            field=models.CharField(default=1900, max_length=4, verbose_name=b'End Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_year',
            field=models.CharField(default=1900, max_length=4, verbose_name=b'Start Year'),
            preserve_default=False,
        ),
    ]
