# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0009_auto_20171025_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='university_agency',
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name=b'Membership Type'),
            preserve_default=False,
        ),
    ]
