# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0010_auto_20171107_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='academic_body',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_no',
            field=models.IntegerField(default=21, verbose_name=b'Membership Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Academic Body Name'),
        ),
    ]
