# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0011_auto_20171108_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_year',
            field=models.CharField(default=2099, max_length=4, verbose_name=b'End Year'),
        ),
    ]
