# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0012_auto_20171108_1652'),
        ('moab', '0011_auto_20171108_2213'),
    ]

    operations = [
    ]
