# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moab', '0013_merge_20171108_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_year',
            field=models.CharField(default=2099, max_length=4, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_no',
            field=models.IntegerField(verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Academic Body Name'),
        ),
    ]
