# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20170903_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awardType',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name=b'awardType'),
            preserve_default=False,
        ),
    ]
