# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_awards_awardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='year',
            field=models.CharField(max_length=100, verbose_name=b'Year'),
        ),
    ]
