# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20171025_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='year',
            field=models.CharField(max_length=4, verbose_name=b'Year'),
        ),
    ]
